
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  # note name contained a slash which is invalid
  name: knative-serving-cluster-local-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  # note name contained a slash which is invalid
  name: knative-serving-ingress-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---

{{range $i := until (int .Values.entries)}}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    networking.knative.dev/ingress.class: istio.ingress.networking.knative.dev
  labels:
    networking.internal.knative.dev/ingress: testvs{{$i}}
    serving.knative.dev/route: testvs{{$i}}
    serving.knative.dev/routeNamespace: default
  name: testvs{{$i}}-ingress
  namespace: default
spec:
  gateways:
  - knative-serving-cluster-local-gateway
  - knative-serving-ingress-gateway
  hosts:
  - testvs{{$i}}.default
  - testvs{{$i}}.default.dev-serving.codeengine.dev.appdomain.cloud
  - testvs{{$i}}.default.svc
  - testvs{{$i}}.default.svc.cluster.local
  http:
  - headers:
      request:
        set:
          K-Network-Hash: 12a72f65db15ba3a00ad16b328c40b5398a86cc84ba3239ad37f4d5ef811b0fa
    match:
    - authority:
        prefix: testvs{{$i}}.default
      gateways:
      - knative-serving-cluster-local-gateway
    retries: {}
    route:
    - destination:
        host: testvs{{$i}}.default.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Knative-Serving-Namespace: default
            Knative-Serving-Revision: testvs{{$i}}
      weight: 100
    timeout: 600s
  - headers:
      request:
        set:
          K-Network-Hash: 12a72f65db15ba3a00ad16b328c40b5398a86cc84ba3239ad37f4d5ef811b0fa
    match:
    - authority:
        prefix: testvs{{$i}}.default.dev-serving.codeengine.dev.appdomain.cloud
      gateways:
      - knative-serving-ingress-gateway
    retries: {}
    route:
    - destination:
        host: testvs{{$i}}.default.svc.cluster.local
        port:
          number: 80
      headers:
        request:
          set:
            Knative-Serving-Namespace: default
            Knative-Serving-Revision: testvs{{$i}}
      weight: 100
    timeout: 600s
---
{{end}}
{{range $i := until (int .Values.entries)}}
---
apiVersion: v1
kind: Service
metadata:
  name: service{{$i}}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---
apiVersion: v1
kind: Endpoints
metadata:
  name: service{{$i}}
subsets:
  - addresses:
      - ip: 192.0.2.42
    ports:
      - port: 9376
---
{{end}}

